# test_monte_carlo.py module.
# Does exactly what you think it does.

import numpy as np
import pytest
from core.eskf import ESKF, EKFHealth
from utils.noise import IMUNoiseParams
from test_drift import RealisticIMU

@pytest.mark.slow
class TestMonteCarlo:
    """Monte Carlo Validation Suite for ESKF"""
    
    def run_ensemble(self, num_runs=10, duration_s=10.0, dt=0.01):
        noise = IMUNoiseParams()
        N = int(duration_s / dt)
        
        # We will collect final RMSE and bias errors
        pos_errors = []
        vel_errors = []
        accel_bias_errors = []
        gyro_bias_errors = []
        
        pos_coverage_count = 0
        total_nees_samples = 0
        
        for run_idx in range(num_runs):
            eskf = ESKF(noise)
            eskf._initialized = True
            eskf._gps_origin = {"lat": 0.0, "lon": 0.0, "alt": 0.0}
            
            rng = np.random.default_rng(42 + run_idx)
            imu = RealisticIMU(noise, rng, temp_drift=True)
            
            # Ground truth
            true_pos = np.zeros(3)
            true_vel = np.zeros(3)
            
            # True biases generated by the IMU simulator
            true_accel_bias = imu.accel_bias.copy()
            true_gyro_bias = imu.gyro_bias.copy()
            
            for i in range(N):
                a, g = imu.sample(np.array([0, 0, -9.80665]), np.zeros(3), dt, i*dt)
                eskf.predict(a, g, dt)
                
                if i % 100 == 0:
                    lat = 0.0 + rng.normal(0, 1e-6)
                    lon = 0.0 + rng.normal(0, 1e-6)
                    alt = 0.0 + rng.normal(0, 0.5)
                    eskf.update_gps(lat, lon, alt, hdop=1.0)
            
            # Calculate 3-sigma bound coverage
            # True error: dx = true_pos - x_est
            # Covariance: P_pos = eskf.P[0:3, 0:3]
            # NEES = dx.T * P_pos^-1 * dx
            # Chi-square 99% for 3DOF is 11.34
            P_pos = eskf.P[0:3, 0:3]
            dx = true_pos - eskf.x[0:3]
            try:
                nees = dx.T @ np.linalg.solve(P_pos, dx)
                if nees < 11.34:
                    pos_coverage_count += 1
                total_nees_samples += 1
            except np.linalg.LinAlgError:
                pass
                
            pos_err = np.linalg.norm(dx)
            vel_err = np.linalg.norm(true_vel - eskf.x[3:6])
            
            ab_err = np.linalg.norm(true_accel_bias - eskf.x[10:13])
            gb_err = np.linalg.norm(true_gyro_bias - eskf.x[13:16])
            
            pos_errors.append(pos_err)
            vel_errors.append(vel_err)
            accel_bias_errors.append(ab_err)
            gyro_bias_errors.append(gb_err)
            
        return {
            "pos_rmse": np.sqrt(np.mean(np.array(pos_errors)**2)),
            "vel_rmse": np.sqrt(np.mean(np.array(vel_errors)**2)),
            "ab_rmse": np.sqrt(np.mean(np.array(accel_bias_errors)**2)),
            "gb_rmse": np.sqrt(np.mean(np.array(gyro_bias_errors)**2)),
            "pos_coverage": pos_coverage_count / max(1, total_nees_samples)
        }
        
    def test_10_run_monte_carlo_bounds(self):
        """Run a 10-run ensemble (for unit testing speed) and verify convergence bounds."""
        res = self.run_ensemble(num_runs=10, duration_s=20.0)
        
        print("\n--- Monte Carlo Results (N=10) ---")
        print(f"Pos RMSE: {res['pos_rmse']:.3f} m")
        print(f"Vel RMSE: {res['vel_rmse']:.3f} m/s")
        print(f"Accel Bias RMSE: {res['ab_rmse']:.4f} m/s^2")
        print(f"Gyro Bias RMSE: {res['gb_rmse']:.4f} rad/s")
        print(f"3-Sigma Pos Coverage (Expected ~99%): {res['pos_coverage']*100:.1f}%")
        
        # Assertions to ensure bias observability is actually working!
        # If biases don't converge, these RMSEs will be huge.
        assert res['pos_rmse'] < 5.0
        assert res['vel_rmse'] < 2.0
        assert res['ab_rmse'] < 0.2
        assert res['gb_rmse'] < 0.05
        
        # Ensure the filter isn't completely overconfident on average
        # Allow some slack for non-linearities, but should bound the truth most of the time
        assert res['pos_coverage'] > 0.50, f"Filter is severely overconfident! Coverage only {res['pos_coverage']*100:.1f}%"

if __name__ == "__main__":
    pytest.main([__file__, "-v", "-s"])
